# Generated by Django 2.0.5 on 2018-05-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='user_id',
            new_name='user',
        ),
    ]
